services:
    caddy:
        image: caddy:2.9-alpine
        container_name: caddy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
            - backend
            - frontend
            - mercure
            - minio
            - mailpit
            - openobserve
        networks:
            - restoflow

    backend:
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        container_name: backend
        working_dir: /app
        volumes:
            - ./backend:/app:delegated
            - ./docker/backend/Caddyfile:/etc/frankenphp/Caddyfile
        tty: true
        stdin_open: true
        expose:
            - "80"
        depends_on:
            - postgres
            - redis
            - minio
            - mailpit
            - mercure
        networks:
            - restoflow

    frontend:
        build:
            context: .
            dockerfile: ./docker/frontend/Dockerfile
        container_name: frontend
        working_dir: /app
        volumes:
            - ./frontend:/app:delegated
            - /app/node_modules
        tty: true
        stdin_open: true
        expose:
            - "5173"
        depends_on:
            - backend
        networks:
            - restoflow

    postgres:
        image: postgres:18-alpine
        container_name: postgres
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        networks:
            - restoflow

    redis:
        image: redis:8-alpine
        container_name: redis
        command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
        volumes:
            - redis_data:/data
        ports:
            - "6379:6379"
        networks:
            - restoflow

    mailpit:
        image: axllent/mailpit:latest
        container_name: mailpit
        expose:
            - "8025"
            - "1025"
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        volumes:
            - mailpit_data:/data
        networks:
            - restoflow

    minio:
        image: minio/minio:latest
        container_name: minio
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
        command: ["server", "/data", "--console-address", ":9001"]
        volumes:
            - minio_data:/data
        expose:
            - "9000"
            - "9001"
        networks:
            - restoflow

    mercure:
        image: dunglas/mercure
        container_name: mercure
        environment:
            - MERCURE_PUBLISHER_JWT_KEY=${MERCURE_PUBLISHER_JWT_KEY}
            - MERCURE_SUBSCRIBER_JWT_KEY=${MERCURE_SUBSCRIBER_JWT_KEY}
            - MERCURE_CORS_ALLOWED_ORIGINS=${MERCURE_CORS_ALLOWED_ORIGINS}
        volumes:
            - mercure_data:/var/lib/mercure
        expose:
            - "80"
        networks:
            - restoflow

    openobserve:
        image: openobserve/openobserve:latest
        container_name: openobserve
        environment:
            - ZO_ROOT_USER_EMAIL=${ZO_ROOT_USER_EMAIL}
            - ZO_ROOT_USER_PASSWORD=${ZO_ROOT_USER_PASSWORD}
            - ZO_DATA_DIR=/data
            - ZO_HTTP_PORT=5080
        volumes:
            - openobserve_data:/data
        expose:
            - "5080"
        networks:
            - restoflow

volumes:
    postgres_data:
    redis_data:
    minio_data:
    mercure_data:
    caddy_data:
    caddy_config:
    openobserve_data:
    mailpit_data:

networks:
    restoflow:
